# Generated by Django 3.2.4 on 2023-04-05 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentuser',
            old_name='images',
            new_name='image',
        ),
    ]
