# Generated by Django 3.2.4 on 2023-04-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20230406_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='image',
            field=models.ImageField(null=True, upload_to='static/media/'),
        ),
    ]
