# Generated by Django 3.2.4 on 2023-04-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_studentuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='password',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
