# Generated by Django 3.2.4 on 2023-04-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_remove_studentuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=30)),
                ('ppic', models.ImageField(null=True, upload_to='static/profile/')),
                ('passwd', models.CharField(max_length=60)),
                ('address', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='StudentUser',
        ),
    ]
