# Generated by Django 3.2.4 on 2023-05-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=300),
        ),
    ]
