# Generated by Django 3.2.4 on 2022-09-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_register_ppic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='ppic',
            field=models.ImageField(null=True, upload_to='static/profile/'),
        ),
    ]
